### ISSUE TITLE
ZMQ portability

### ISSUE THREAD

**Issue by zmughal** [EntropyOrg/p5-Devel-IPerl#1]
- need to see if ZMQ can be installed on all systems
- perhaps http://p3rl.org/ZMQ::FFI may help?
- The IPython messaging protocol uses ZeroMQ. This might make the kernel not as portable as it could
  be. There are several solutions to this.
  - Create a new wire protocol entirely using Perl and sockets. Frontends that support this protocol
     would need to be written.
  - Try to ensure ZeroMQ works everywhere. There exist the Alien::ZeroMQ and ZeroMQ::FFI distributions
     which could help avoid compilation on some platforms.
- Make sure Alien::ZMQ works everywhere. Perhaps [it can use Alien::Base](https://github.com/chazmcgarvey/p5-Alien-ZMQ/issues/2).
- https://github.com/lestrrat/p5-ZMQ/issues/13, https://github.com/chazmcgarvey/p5-Alien-ZMQ/issues/1

**Comment by zmughal** [comment]
Next step: perhaps create an Alien::Base-based `Alien::LibZMQ3`, `Alien::ZMQ4`.

**Comment by zmughal** [comment]
TODO: test <https://github.com/zmughal/p5-Alien-ZMQ4> on Windows

**Comment by asimonov** [comment]
Zaki, i am trying to install iperl on windows and need to check what configuration you used. Cannot find your email anywhere. What is the best way to contact?

**Comment by zmughal** [comment]
Hi, you can reach me at `zmughal@cpan.org`.

Just to answer your question, I currently do not have a Windows build working. I am planning to get to this at some point, but have been really busy lately. I will try to set aside time for this in the coming weeks and will let you know my progress.

In the meantime, I would recommend using Docker or a virtual machine with Linux to install IPerl. Someone has made a Dockerfile [here](https://gist.github.com/dbiesecke/c57874957bed9812c5f0).

Another approach is to install [JupyterHub](https://github.com/jupyterhub/jupyterhub) on a Linux machine. This will act as a server that will let you create Jupyter/IPerl notebooks from any machine that can reach it.

I hope that helps!

**Comment by zmughal** [comment]
Fixed by <https://github.com/EntropyOrg/p5-Devel-IPerl/pull/82>.

**Comment by zmughal** [comment]
Note:

The results of getting this issue closed:

# Distributions created

- <https://github.com/zmughal/p5-Alt-Alien-ZMQ-Alien-ZMQ-latest>
- <https://github.com/zmughal/p5-Net-Async-ZMQ>
- <https://github.com/zmughal/p5-Alien-ZMQ-latest>

# PRs opened

- <https://github.com/lestrrat/p5-ZMQ/pull/77>
- <https://github.com/lestrrat/p5-ZMQ/pull/78>
- <https://github.com/keedi/Markdown-Pod/pull/9>
- <https://github.com/keedi/Markdown-Pod/pull/10>
