### ISSUE TITLE
Registering IPerl as IPython3 plugin

### ISSUE THREAD

**Issue by bgruening** [EntropyOrg/p5-Devel-IPerl#37]
Enhance the setup script to register IPerl as plugin in the normal `ipython notebook`.

**Comment by zmughal** [comment]
I believe this is related to the kernel registry in #16. I'll take a look soon. :-)

**Comment by zmughal** [comment]
Done in <https://github.com/EntropyOrg/p5-Devel-IPerl/tree/feature/kernel-spec> branch.

Here's a screenshot:
![selection_303](https://cloud.githubusercontent.com/assets/94489/7443099/adcf93ba-f0f8-11e4-8c8b-a05c2f4c23d8.png)

**Comment by demianriccardi** [comment]
!!YAY!!
