### ISSUE TITLE
issue saving the notebook after redefined subroutine

### ISSUE THREAD

**Issue by demianriccardi** [EntropyOrg/p5-Devel-IPerl#38]
if a subroutine is saved in a cell and then recompiled, the notebook can't be saved.  The redefined subroutine issue is avoidable, but it may be a common issue.

Notebook Validation failed: [u'Subroutine kgd_tp redefined at reply input line 12.\n'] is not of type u'string':
[
 "Subroutine kgd_tp redefined at reply input line 12.\n"
]

**Comment by demianriccardi** [comment]
simple work around is to copy the code in the cell, copy into new cell, and then delete the cell that had the subroutine redefine.

**Comment by zmughal** [comment]
I think this is because I send an array of warnings back to IPython in the latest version of IPerl. I was seeing this issue too when I was working on that feature. I'll try to replicate and fix it soon.

**Comment by zmughal** [comment]
Which version of IPython and IPerl are you using?

I can't seem to replicate it under the IPerl under Git master and IPython 3.0.0.

This is what I am using to test it.

![selection_300](https://cloud.githubusercontent.com/assets/94489/7059552/48c121dc-de38-11e4-9b22-3f42b8c88c99.png)

**Comment by demianriccardi** [comment]
Bah!  I’m on another computer right now, and I just installed the most recent of everything, and it seems to work fine now.  I’m sorry for your lost time, Zaki!!

**Comment by zmughal** [comment]
Not a problem! I went over it while dinner was cooking on the stove! :-P

Also, you might have noticed that I have moved lots of things over to the EntropyOrg organisation. ;-)

**Comment by demianriccardi** [comment]
I just did!  Very nice!!!
