### ISSUE TITLE
Do iperl notebooks now work with windows?

### ISSUE THREAD

**Issue by demianriccardi** [EntropyOrg/p5-Devel-IPerl#41]
Some of my students use windows

**Comment by zmughal** [comment]
The only dependency that I would be worried about installing is ZMQ::LibZMQ3.

I'll mess about with it later this week and see what I can find. I'm sure if it is important enough, we can get Strawberry Perl to ship with the library.

Related issue: <https://github.com/EntropyOrg/p5-Devel-IPerl/issues/1>.

**Comment by zmughal** [comment]
I've taken a first step towards making IPerl work easily on Windows: <https://github.com/chazmcgarvey/p5-Alien-ZMQ/pull/5>. Getting `libzmq` to compile with `Alien::ZMQ`.

**Comment by zmughal** [comment]
I'm still working on this. I just haven't had time to fix `libzmq 4.x` to compile statically on Windows.

**Comment by zmughal** [comment]
I think I have a fix for this now that I understand the Windows build process better.

**Comment by zmughal** [comment]
Fixed by <https://github.com/EntropyOrg/p5-Devel-IPerl/pull/82>. Will have instructions and a new release up soon.
