### ISSUE TITLE
Portability: MSWin32: no POSIX fork

### ISSUE THREAD

**Issue by zmughal** [EntropyOrg/p5-Devel-IPerl#43]
Should not use `IO::Async`'s `spawn_child` function since Windows does not support POSIX `fork()`.

**Comment by stphnlyd** [comment]
I looked at this a little bit today. Besides spawn_child, IO::Async::Handle+IO::Handle is also not usable because Windows does not support FD. I guess we might just use zmq_poll(), and even separate heartbeat into a separate script execution.
