### ISSUE TITLE
Create Dockerfile for IPerl

### ISSUE THREAD

**Issue by zmughal** [EntropyOrg/p5-Devel-IPerl#57]
- IPerl
- PDL (see https://github.com/PDLPorters/devops/issues/5)
- [JupyterHub](https://github.com/jupyterhub/jupyterhub)
  
  ``` shell
  sudo apt-get install --no-install-recommends npm nodejs-legacy python3-pip build-essential python3-dev
  sudo npm install -g configurable-http-proxy
  sudo pip3 install jupyterhub notebook
  ```

https://gist.github.com/dbiesecke/c57874957bed9812c5f0

**Comment by pablrod** [comment]
Using version 0.006 but working:
* https://hub.docker.com/r/stuffox/jupyter-perl/
* https://github.com/marghidanu/jupyter-perl

**Comment by zmughal** [comment]
And <https://github.com/milescsmith/jupyter-perl>!
