### ISSUE TITLE
ipython-notebook not anymore available in Debian/stretch

### ISSUE THREAD

**Issue by eserte** [EntropyOrg/p5-Devel-IPerl#70]
https://metacpan.org/source/ZMUGHAL/Devel-IPerl-0.006/README.md lists ipython-notebook as a system dependency. However, in the next stable Debian (stretch) this package is not available anymore (or maybe it's just renamed).

**Comment by zmughal** [comment]
Thanks for the heads up. I will be updating the dist and docs for the post-Project Jupyter split. For that, we will need to use the `python3-notebook` Debian package.

**Comment by zmughal** [comment]
You may want to switch to using `jupyter-console` and `jupyter-notebook` since it directly installs just the Project Jupyter packages.

**Comment by eserte** [comment]
OK. I will amend CPAN::Plugin::Sysdeps::Mapping soon with this information.
