### ISSUE TITLE
CPAN release without Cairo dependency

### ISSUE THREAD

**Issue by demianriccardi** [EntropyOrg/p5-Devel-IPerl#78]
The Cairo dependency makes the install challenging on OS X.  Is there a new release in the near future that pulls out the Chart::Clicker dependency?

**Comment by demianriccardi** [comment]
was able to install manually by pulling the chart clicker plugin.  OS X build note: I had to install zeromq via homebrew.

**Comment by zmughal** [comment]
Hi @demianriccardi! I was actually working on fixing this on a branch this summer, but haven't made the push for a final release yet. I should be able to get to this now that I have some tuits.

**Comment by zmughal** [comment]
v0.007 is headed to CPAN now. I'll be also releasing the split off dists for the ChartClicker and PDLGraphicsGnuplot plugins soon.

**Comment by zmughal** [comment]
Closing this since the release seems to be working.
