### ISSUE TITLE
Setting standard stream and source encoding to UTF-8

### ISSUE THREAD

**Issue by dlukes** [EntropyOrg/p5-Devel-IPerl#92]
Trying to print accented UTF-8 characters, I get the "Wide character in print" warning:

```perl
print "žůžová čtvrteční řácká kúra"
# prints: Å¾Å¯Å¾ovÃ¡ ÄtvrteÄnÃ­ ÅÃ¡ckÃ¡ kÃºra
# and warns: Wide character in print at reply input line 1.
```

I know how to solve this in a script:

```perl
use utf8;  # set source encoding
use open qw(:std :encoding(UTF-8));  # set encoding of standard streams
```

Is there a way to hook this setup into IPerl? I tried modifying the `perl` arguments (adding `-Mutf8 -Mopen qw(:utf8 :encoding(UTF-8))`) in `kernel.json`, but that file keeps getting overwritten each time IPerl is started.

As a temporary workaround, I hardcoded the arguments into the `iperl` command line wrapper, but that's obviously not the right way to do it :) Any recommendations as to how to do it right? Or is it simply not supported currently?

**Comment by zmughal** [comment]
Fixed by commit <https://github.com/EntropyOrg/p5-Devel-IPerl/commit/17691a425d45bc58b036efa7a6b5856c8e571579>.

Thanks @dlukes!
