### ISSUE TITLE
What is the equivalent of %%html and %%javascript when using the perl kernel?

### ISSUE THREAD

**Issue by adamcrussell** [EntropyOrg/p5-Devel-IPerl#94]
If you use Jupyter with a Python kernel you can use aliases such as %%html and %%javascript. For example:

    %%html
    <div id="d3-example"></div>
    <style>
    .node {stroke: #fff; stroke-width: 1.5px;}
    .link {stroke: #999; stroke-opacity: .6;}
    </style>

will create a new div which could be populated  by some d3.js code 

    %%javascript
     var svg = d3.select("#d3-example").select("svg")
     if (svg.empty()) {
    svg = d3.select("#d3-example").append("svg")
          .attr("width", width)
          .attr("height", height);
    }

Is there some equivalent syntax for this when using the Perl kernel?

Edit: 

Apparently these are called "magics" https://ipython.readthedocs.io/en/stable/interactive/magics.html 
perhaps my question should then be, more broadly, is there any support for magics with the Perl kernel?

**Comment by zmughal** [comment]
Not at this time. I hesitated to put something like that in there when it could interfere with syntax. For this kind of thing, I typically use `IPerl->html(<<'EOF');`

**Comment by adamcrussell** [comment]
> Not at this time. I hesitated to put something like that in there when it could interfere with syntax. For this kind of thing, I typically use `IPerl->html(<<'EOF');`

Ok, got it, thanks! Feel free to close this thread!
